trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# Restore
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Build
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: >
      /p:DeployOnBuild=true
      /p:WebPublishMethod=Package
      /p:PackageAsSingleFile=true
      /p:SkipInvalidConfigurations=true
      /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip"
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

# 🚀 Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-service-conn'
    appName: 'dot-net-web-app--publish-with-code-cicd'
    appType: 'webApp'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'