trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

# Restore packages
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

# Build project
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# Publish to folder
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: false   # Keep as folder, not zip

# Optional: Publish artifacts for debugging
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/publish'
    artifactName: 'drop'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-service-conn'
    appName: 'dot-net-web-app--publish-with-code-cicd'
    package: '$(Build.ArtifactStagingDirectory)/publish'
    appType: 'webApp'